services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: national_exams_db
      MYSQL_USER: django
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: national_exams_db
      DB_USER: django
      DB_PASSWORD: django_pass
    volumes:
      - .:/app

volumes:
  mysql_data:
